<a href="https://colab.research.google.com/github/Ruqyai/Colab/blob/master/Copy_of_Refresh_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# python for Data Sci

In [0]:
# python and all programming languages can do basic math (add, subtratct , multiply, division)
print(5+5)
print(5-5)
print(5*5)
print(5/5)

10
0
25
1.0


in python there are additional operators power`**` and modulo `%`

In [0]:
print(5**3) # means 5*5*5
print(11%2) # means the reminder of the divison

125
1


## Example:
Suppose you have $100, which you can invest with a 10%
return each year. After one year, it's 100×1.1=110 dollars,
and after two years it's 100×1.1×1.1=121.

In [0]:
#TODO: Add code to calculate how much money you end up with after 7 years.
print(100 * 1.1 ** 7)


194.87171000000012
194.87171000000012


## variables 
* case sensitive
* no start with numbers
* no symbols just _  

## Types 
there are commoan types in python (int, float, string, bool ,list, set, dictioninary)
to know the type write `type(varible name)` 

In [0]:
# Create a variable savings with the value 100.
# Check out this variable by typing print(savings) in the script.
# Check out this variable type by typing print(type(savings)) in the script.

In [0]:
savings = '100'
result =str(100 * 1.10 ** 7)

# Fix the printout
print("I started with $" + savings + " and now have $" + result + ". Awesome!")
print(type(savings))
print(type(result))

I started with $100 and now have $194.87171000000012. Awesome!
<class 'str'>
<class 'str'>


###  we saw int and float values now lets another data types 
**TODO:** Create a new string, desc, with the value "pyhton Course".  

**TODO:** Create a new boolean, profitable, with the value True

In [0]:
# Create a variable desc
desc = "pyhton Course"
# Create a variable profitable
profitable = True

String vlaues must be between tow double or single quotes Ex: "Hello" or 'Hi'. You can merge between strings with + operator.

boolean values can be `True` or `False` first capital letter is important also can be 0 or 1

## we can convert between some python types
we can convert string value contains numbers to int or float but we can't convert letters to float or int
we can convert between int and float but in convert int to float the numbers after the fraction point removed

In [0]:
# Definition of pi_string
pi_string = "3.1415926"

# TODO: Convert pi_string into float: pi_float and then print the type of it
pi_float =float(pi_string)

## all these types store single values and our probelm in data scinece have many datapoint and it's hard to store each value in variable so we're using list to hold many values in one variable

**List features**
* name a collection of values 
* contain any type
* Contain different type

In [0]:
fam = ["lyla",1.65,"Naser",1.70,"mom",1.67,"dad",1.89]
fam

['lyla', 1.65, 'Naser', 1.7, 'mom', 1.67, 'dad', 1.89]

In [0]:
# You can access the list by its index the index start from 0 to (length of list-1)
# so fam[0] will print "lyla" and fam[7] will print 1.89
print(fam[0])
print(fam[7])
#TODO: print the second element from the fam list
print(fam[1])

lyla
1.89
1.65


In [0]:
# also you can go backword by using minus sign for eaxmple fam[-1] will print the last element

#TODO: print "mom" from the list using backward index
print(fam[-4])

mom


### list slicing :  list[ start : end ]

**Start inclusive ---------     end exclusive**

for example if we want to get the name "Naser" and his tall from our `fam` varibale we will insert the index of "Naser" which is 2 and the index of his tall+1 which is 4 so it will be `fam[2:4]`  

In [0]:
#TODO: print "dad" and his tall from fam list using list slicing
fam[6:8]

['dad', 1.89]

In [0]:
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

#TODO: Use slicing to create a list, downstairs, that contains the first 6 elements of areas.
 #Use slicing to create downstairs
downstairs = areas[0:6]


# TODO: Do a similar thing to create a new variable, upstairs, that contains the last 4 elements of areas.
# Use slicing to create upstairs
upstairs = areas[6:11]


# TODO: Print both downstairs and upstairs using print().

# Print out downstairs and upstairs
#print (downstairs,upstairs)
print(downstairs)
print(upstairs)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
['bedroom', 10.75, 'bathroom', 9.5]


If you don't specify the `start` index, Python figures out that you want to start your slice at the beginning of your list. If you don't specify the `end` index, the slice will go all the way to the last element of your list

**Try this in the cell below**

x = ["a", "b", "c", "d"]

x[:2]

x[2:]

x[:]

In [0]:
x = ["a", "b", "c", "d"]

print(x[:2])

print(x[2:])

print(x[:])

['a', 'b']
['c', 'd']
['a', 'b', 'c', 'd']


# Import packges
In python we can import packges that profiessinal developers made them and make our code life easier in data sci there are many comman packages we use such as `numpy`, `pandas`, `matplotlib`, `scikit learn` and there are more packages

## import numpy and using it 
to import package we to type import then packcage name and we can give it local name for shortcut and the comman local name for numpy is np

In [0]:
# TODO: import numpy package as np
import numpy as np

You can convert normal list to array using `np.array()`

In [0]:
scores = [20,40,60,70,30,50]
# TODO: convert scores list to array and assign the value to np_scores
np_scores= np.array(scores)
print (scores, type(scores))
print (np_scores, type(np_scores))


[20, 40, 60, 70, 30, 50] <class 'list'>
[20 40 60 70 30 50] <class 'numpy.ndarray'>


### Array vs List
the main diffrence between them 

**Array**: can apply math opreations on it like +,*,/,-

**List** if you used + operator it means merage the values not add them


In [0]:
scores_1 = [20,40]
score_2 = [60,80]
#TODO: add scores_1 with scores_2 and print the output
add_scores =scores_1 + score_2
print('list', add_scores)

# TODO: convert scores_1 and scores_2 to array and add them then print the output
arr_score_1=np.array(scores_1)
arr_score_2=np.array(score_2)
arr_add_scores=arr_score_1+arr_score_2
print('array',arr_add_scores)



list [20, 40, 60, 80]
array [ 80 120]


### there are similar features between the array and list like indexing and slicing

In [0]:
players = np.array(["ahmed","Yasser","Naser","Fahad","Ali","Youssef","Anas","Jameel"])
#TODO: print Ali from the players array
print(players[4])
#TODO: assign the first 4 players to red_team and the last 4 players to blue_team
red_team=players[:4]
blue_team=players[4:]
print(red_team)
print(blue_team)

Ali
['ahmed' 'Yasser' 'Naser' 'Fahad']
['Ali' 'Youssef' 'Anas' 'Jameel']


In [0]:
# TODO: Create a 1D array of numbers from 0 to 9 with arange() function
ID =np.arange(10)
print(ID)

[0 1 2 3 4 5 6 7 8 9]


In [0]:
#TODO: Create a 3×3 numpy array of all True’s with boolean type using full function
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [0]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [0]:
# you can but condition inside the index brackets to print all values that condation is true
#TODO:  extract items that satisfy a given condition from 1D array element is even
#arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Input
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Solution
arr[arr % 2 == 1]
#> array([1, 3, 5, 7, 9])

array([1, 3, 5, 7, 9])

In [0]:
# TODO: Convert a 1D array to a 2D array with 2 rows using reshape function
#arr = np.arange(10)
#hint: Setting cols to -1 automatically decides the number of cols

arr = np.arange(10)
arr.reshape(2, -1)  # Setting to -1 automatically decides the number of cols

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## for more numpy exercises visit the [website](https://www.machinelearningplus.com/python/101-numpy-exercises-python/)

### Now it's the time of condition 
In python you can logic operators like bigger than `>`, less than`<`, equal`==` and not equal `!=`
these operators returns boolean value `True` or `False` it basiclly if the condition is True do something if something else to another things

In [0]:
# Examples 
v1 = 5
v2 = 10
if v1>v2:
    print("Correct Answer")
    print(v1>v2)
else:
    print("Wrong answer")
    print(v1>v2)

Wrong answer
False


It can be more than one if statments and it can be nested

In [0]:
a = 2
b = 4
c = 6

if a > b:
    if a> c: # if statment inside if statment
        print(str(a)+" is the largest number")
elif b > c: # elif used when you create multiple if statments 
    print(str(b)+" is the largest number")
else:
    print(str(c)+" is the largest number")

6 is the largest number


It was a quick intro to the if statments and now what if you want to repeat an instruction few times should you write down the instruction five times or 1000 times it's very hard so we can use **for loop** to repeat the instructions and to read data from continers like lists or arrays 

In [0]:
#Example of foor loop
for i in range(5): # it means give the variable i value in range 5 * range(5) means 0,1,2,3,4 = repeat 5 times
    print("Hola")

Hola
Hola
Hola
Hola
Hola


In [0]:
# you can read elements from list also
friends = ["Ahmed", "Mohamed","Omar","Waleed"]
for i in friends: # means for variable i in the list friends 
    print(i) 
# you can also add iterate by range
for i in range(len(friends)): # len to get the length of the list (how many times you want to iterate)
    print(i)
# It's same in some points and not same in some else

Ahmed
Mohamed
Omar
Waleed
0
1
2
3


We write code to make functions and write functions to make classes

The function is like a continaer to your code have specific name and do specific task let us see some example

In [0]:
def add(a,b): # def here means define function with name (add) takes tow values
    print(a+b) #here print the value of a+b
# see the function weill not print and value and wont work if we don't called it now let's called the function
add(6,6)
#TODO: add sub, multiple, divide functions and print them out

12


In [0]:
fName = "Ahmed"
def print_value(x):
    print(x)
    
# we can pass variable with not same name of the argument value
print_value(fName)
# argument variable effects only inside the function

Ahmed
